clear
echo
echo $cy"================================================================"
echo $pu"Github   : https://github.com/Makky2693"
echo $pu"WhatsApp : +92 313-1694897"
echo $pu"Facebook : https://m.facebook.com/Makky"
echo $pu"YouTube  : http://youtube.com/c/Makky2693"
echo $cy"================================================================"
echo
echo $cy"   ╔═══════════╗"
echo $cy" ╔═╝███████████╚═╗"
echo $cy"╔╝███████████████╚╗"
echo $cy"║█████████████████║"
echo $cy"║█████████████████║	SELAMAT ANDA TERTIPY"
echo $cy"║█████████████████║	2019 KOK GRATISAN :V"
echo $cy"║█╔█████████████╗█║	MODAL DIKIT EA"
echo $cy"╚╦╝███▒▒███▒▒███╚╦╝	TERCIUM AROMA KEKESALAN"
echo $cy"╔╝██▒▒▒▒███▒▒▒▒██╚╗	TIDAK ADA WIFI"
echo $cy"║██▒▒▒▒▒███▒▒▒▒▒██║	YANG AMAN :v"
echo $cy"║██▒▒▒▒▒███▒▒▒▒▒██║"
echo $cy"║██▒▒▒▒█████▒▒▒▒██║"
echo $cy"╚╗███████████████╔╝"
echo $cy" ╚══╦╝██▒█▒██╚╦══╝"
echo $cy"    ║█████████║"
echo $cy"    ║█║██║██║█║"
echo $cy"    ╚═╩══╩══╩═╝"
